### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by rlanzafame**
A few things:
- updating structure of subdirectory tests to include the books (and to match jupyter book! see [here](https://github.com/jupyter-book/jupyter-book/tree/main/tests))
- updating documentation in README
- (hopefully) updating the documentation in the sphinx page

### CODE REVIEW

**Comment by rlanzafame** [comment]
@junwon1022 can you look at tests subdirectory cahnge
@Tom-van-Woudenberg can you look at readme? idea is to keep it "slim" - actually once i learn to use the sphinx stuff  i will move the tools descriptions there, so ignore that part and chack out the top and bottom of the readme. maybe it provides a template for how we can structure the README files in the other tool repo's?

**Review by Tom-van-Woudenberg — APPROVED** [review]
I've made some edits @rlanzafame 
I don't see the need for an introduction on teachbooks (partly because this readme is used in the manual too in which the overarching intentions are already clear).
Furthermore, I added the contribute chapter back in because I think it's necessary to make clear how to do so.

**Comment by Tom-van-Woudenberg** [comment]
@rlanzafame , can you have a look at my changes to see if you agree? Otherwise, feel free to merge!

**Comment by junwon1022** [comment]
> @junwon1022 can you look at tests subdirectory cahnge @Tom-van-Woudenberg can you look at readme? idea is to keep it "slim" - actually once i learn to use the sphinx stuff i will move the tools descriptions there, so ignore that part and chack out the top and bottom of the readme. maybe it provides a template for how we can structure the README files in the other tool repo's?



> @junwon1022 can you look at tests subdirectory cahnge @Tom-van-Woudenberg can you look at readme? idea is to keep it "slim" - actually once i learn to use the sphinx stuff i will move the tools descriptions there, so ignore that part and chack out the top and bottom of the readme. maybe it provides a template for how we can structure the README files in the other tool repo's?

I've looked through the directory structure change, and it seems like a good change to match the jupyter book!

**Comment by rlanzafame** [comment]
@Tom-van-Woudenberg i thought we agreed at least TeachBooks package doesn't need to keep the README on the manual branch in sync with the manual? let's discuss next week the pros and cons again :)
my main issue is that i feel the current setup prevents be from writing what i want to the target audience, in both places (repo/sphinx-doc and manual).

**Comment by rlanzafame** [comment]
OK a bit more work done @Tom-van-Woudenberg and @junwon1022 
1. I think i figured out the formatting of the documentation page but because i can't get it to build locally yet i can't confirm until we complete this PR.
2. I tweaked README again (@Tom-van-Woudenberg the new subsection at the bottom is an example of something that really needs to be in README but obviously not in the manual)
3. I noticed that the file name for the draft/release thing is still publish.py.... @junwon1022 can you see if you can take a quick look at issue #36 and incorporate it in this PR? if not now, just add comment in the issue and we can incorporate it later

**Comment by Tom-van-Woudenberg** [comment]
@rlanzafame, haha sorry... I thought we concluded that the external toc thing will make it easy enough and there's a lot of overlap between those audiences. But let's discuss again indeed! (Btw, I think the last section could also be in the manual ;))
If you think we should keep the longer introduction to what teachbooks is in every tool's readme I'd be fine with that (I may have been too strict). We can delete that section in the manual branch anyway if we keep using that.

**Comment by rlanzafame** [comment]
we can close this once @Tom-van-Woudenberg and i discuss the readme setup in person and update it one more time!

**Pull request merged**
