### PR TITLE
Jupyterbook options

### PR DESCRIPTION
**Pull request by junwon1022**
This pull request regards issue #22.

Jupyter book options had been added, so that they could be executed when the server starts running. (Line 60, 99 on serve.py)

To make sure the option is working, an example "--all" has been added (line 74 on main.py) and printing of the command (line 75~80 on serve.py).

### CODE REVIEW

**Comment by Tom-van-Woudenberg** [comment]
The intention was that if you do `teachbooks build book --any_option` it should take that `--any_option` with it to its nested command `jupyter-book build --any_option`

**Comment by junwon1022** [comment]
The current implementation only adds up a command when the server starts running, but there are no concrete options yet. This pull request will be marked as a draft until there are any visible options developed.

**Comment by junwon1022** [comment]
Now the commands such as teachbooks build book --any_option is interpreted as jupyter-book build --any_option, and executed properly. You could test one by typing "teachbooks build book --all ", where it'll build the entire book via sphinx.

**Review by Tom-van-Woudenberg — CHANGES_REQUESTED** [review]
Tested locally, but `teacbhooks build book --all` doesn't work, it gives:
```
Usage: teachbooks build [OPTIONS] PATH_SOURCE
Try 'teachbooks build --help' for help.

Error: No such option: --all
(jupbookmanual)
```

Futhermore, it seems you've included a book now in this package, is that needed?

**Comment by junwon1022** [comment]
@Tom-van-Woudenberg 
Thank you for your feedback. I've investigated the issue and would like to clarify a few points:

I've verified the functionality by:

1. Performing a fresh clone of the repository
2. Confirming that teachbooks build book --all works as expected

스크린샷 2024-11-14 225522

Could you please confirm you're working on the jupyterbook_options branch? The screenshot shows the command executing successfully on my end. First part is the error message when I execute on the main branch, and the second part is a succesful build from the jupyterbook_options branch.

Regarding the book files: They are generated as output from the "teachbooks build book --all" command. I initially included them for easier testing and verification of changes, but I can remove them from the commit if you prefer to keep the repository cleaner. Please let me know your preference on this.

**Comment by Tom-van-Woudenberg** [comment]
> @Tom-van-Woudenberg 
> Thank you for your feedback. I've investigated the issue and would like to clarify a few points:
> 
> I've verified the functionality by:
> 
> 1. Performing a fresh clone of the repository
> 2. Confirming that teachbooks build book --all works as expected
> 
> 스크린샷 2024-11-14 225522
> 
> Could you please confirm you're working on the jupyterbook_options branch? The screenshot shows the command executing successfully on my end. First part is the error message when I execute on the main branch, and the second part is a succesful build from the jupyterbook_options branch.
> 
> Regarding the book files: They are generated as output from the "teachbooks build book --all" command. I initially included them for easier testing and verification of changes, but I can remove them from the commit if you prefer to keep the repository cleaner. Please let me know your preference on this.

Hmmm, I really thought I used your jupyterbook_options branch. I'll try again tomorrow.

If we set up some automatic testing I think that would be nice, but otherwise I think those book files are confusing. Unless you think otherwise, you probably have more experience with this

**Comment by junwon1022** [comment]
> I tried again, it does work. But before merging @junwon1022 :
> 
> * convince me that we need the example in the repo itself
> * or remove the example ;)

The reason I put the yml and md files (_config.yml, _toc.yml, chapter1.md etc) is because the "teachbooks build book --all" command does not function without the files. Therefore the yml and md files are needed for sure. However, the example book is not really needed in the moment, and it's really easy to remove them since a single 'teachbooks clean book' command will delete the entire book. I can do that right away.

**Comment by Tom-van-Woudenberg** [comment]
> The reason I put the yml and md files (_config.yml, _toc.yml, chapter1.md etc) is because the "teachbooks build book --all" command does not function without the files. Therefore the yml and md files are needed for sure. However, the example book is not really needed in the moment, and it's really easy to remove them since a single 'teachbooks clean book' command will delete the entire book. I can do that right away.

But the teachbooks argument doesn't use the internal _config.yml etc. files? It should only use the book on which the function is applied?

**Comment by junwon1022** [comment]
> > The reason I put the yml and md files (_config.yml, _toc.yml, chapter1.md etc) is because the "teachbooks build book --all" command does not function without the files. Therefore the yml and md files are needed for sure. However, the example book is not really needed in the moment, and it's really easy to remove them since a single 'teachbooks clean book' command will delete the entire book. I can do that right away.
> 
> But the teachbooks argument doesn't use the internal _config.yml etc. files? It should only use the book on which the function is applied?

I'm guessing that those files should be created by the users themselves, am I correct? I just added those files to test that the functionality works. Since I know that the options function works now, I could delete them if they're unnecessary. Do you think it's better to clean up the "book" folder?

**Comment by Tom-van-Woudenberg** [comment]
> I'm guessing that those files should be created by the users themselves, am I correct? I just added those files to test that the functionality works. Since I know that the options function works now, I could delete them if they're unnecessary. Do you think it's better to clean up the "book" folder?

Yes, I do not see the need of a 'book' folder inside this repo. Unless it is used for (and placed under) tests part of `test.yml`.

**Comment by junwon1022** [comment]
> > I'm guessing that those files should be created by the users themselves, am I correct? I just added those files to test that the functionality works. Since I know that the options function works now, I could delete them if they're unnecessary. Do you think it's better to clean up the "book" folder?
> 
> Yes, I do not see the need of a 'book' folder inside this repo. Unless it is used for (and placed under) tests part of `test.yml`.

The book folder is gone. Maybe I could add them back later for testing purpose, but I agree that they're not needed in the moment. Thank you for your feedback.

**Pull request merged**
