### PR TITLE
Next release: v0.1.0

### LINKED ISSUE #41: teachbooks causes build to fail when branch is set to preprocess
teachbooks package wth --publish option seems to not copy the _ext folder for the temporary APA style setup (_ext contains a local plugin).

doesnt work here: https://github.com/TeachBooks/manual/actions/runs/12199910309
works here: https://github.com/TeachBooks/manual/actions/runs/12200676989

image

### PR DESCRIPTION
**Pull request by rlanzafame**
there are still a few things left...

### CODE REVIEW

**Comment by rlanzafame** [comment]
summary of changes above this point:
- clean out a few more remnants of "publish" by replacing with "release"
- add tests for `teachbooks build`
- update `teachbooks serve`: user-specified path, improved messaging, global constants defining temp directory and default book context (`./book/_build/html`), added simple tests for cli `serve`, `serve path <path>` and `stop` (more needed)
- temporary directory `./book/.teachbooks/server/` changed to `./.teachbooks/server/`. This is expected to happen for the `release` directory (and all future usage of `.teachbooks/` in generaL), but that will be implemented later.
- added `--version` option to CLI

**Comment by rlanzafame** [comment]
+ temporary directory `./book/.teachbooks/server/` changed to `./.teachbooks/server/`. This is expected to happen for the `release` directory (and all future usage of `.teachbooks/` in generaL), but that will be implemented later.

**Comment by rlanzafame** [comment]
Hey @Tom-van-Woudenberg i don't expect you to look at all the code changes. Just confirm that you agree with a (hopefully) standard setup of `dev` into `main` as a way to set up new releases. The generic PR can be "Next Release".

**Review by Tom-van-Woudenberg — DISMISSED** [review]
Didn't go through the code changes as you asked

**Comment by rlanzafame** [comment]
Since the last review by Tom, added this:
- check server status at end of build and print a message accordingly
- temporary fix for including APA style when using `--release build` ("draft" mode)
- updated README to better describe package (taking into account the Manual page will no longer use the README)
- updated pyproject.toml to include GH repo as homepage and release `v0.1.0`

**Pull request merged**
